default: &default
  adapter: postgresql
  encoding: unicode
  username: sattar
  password: sattar
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: SpendiGo_development

test:
  <<: *default
  database: SpendiGo_test

production:
  <<: *default
  database: SpendiGo_production
  username: SpendiGo
  password: <%= ENV["SPENDIGO_DATABASE_PASSWORD"] %>
